version: '3'
services:
  envoy:
    image: envoyproxy/envoy-distroless-dev:8537d2a29265e61aaa0349311e6fc5d592659b08
    restart: unless-stopped
    ports:
      - 10000:10000
      - 9901:9901
    # volumes:
    #   - ./config/envoy/envoy.yaml:/etc/envoy/envoy.yaml
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      # - ./relative-path-volume:/var/data-two
  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/datasources   
  portainer:
    profiles:
      - portainer
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config/portainer/localtime:/etc/localtime:ro
      - "//var/run/docker.sock://var/run/docker.sock"  ## Connect to docker daemon on windows
      - ./config/portainer/portainer-data:/data
    ports:
    - 9001:9000